### ISSUE TITLE
Java error upon `npm start` using the plugin

### ISSUE THREAD

**Issue by stnight** [godu/serverless#28]
I cannot use the plugin with my current setup, it produce an error:

```text
2018-12-20 15:37:10.016:WARN:oejs.AbstractHttpConnection:/
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-12-20 15:37:10.034:WARN:oejs.AbstractHttpConnection:/
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-12-20 15:37:10.245:WARN:oejs.AbstractHttpConnection:/
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
2018-12-20 15:37:10.501:WARN:oejs.AbstractHttpConnection:/
java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
Caused by: 
java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.encodeShardIterator(ShardIterator.java:64)
	at com.amazonaws.services.dynamodbv2.local.shared.access.ShardIterator.toString(ShardIterator.java:53)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:457)
	at com.amazonaws.services.dynamodbv2.local.shared.access.LocalDynamoDBStreamsClient.getShardIterator(LocalDynamoDBStreamsClient.java:267)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBRequestHandler.getShardIterator(LocalDynamoDBRequestHandler.java:289)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:19)
	at com.amazonaws.services.dynamodbv2.local.dispatchers.GetShardIteratorDispatcher.enact(GetShardIteratorDispatcher.java:11)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.packageDynamoDBResponse(LocalDynamoDBServerHandler.java:364)
	at com.amazonaws.services.dynamodbv2.local.server.LocalDynamoDBServerHandler.handle(LocalDynamoDBServerHandler.java:451)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1088)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1024)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.base/java.lang.Thread.run(Thread.java:844)
```

I tried to switch and use the following jdk:
* 12.ea.20-open
* 11.0.1-zulu
* 11.0.1-open
* 10.0.2-open
* 9.0.7-zulu
* 9.0.4-open
* 8.0.192-zulu

Do you know how to resolve this? I'm currently using Ubuntu 18.04

**Comment by AAAstorga** [comment]
Have you been able to find a solution?

**Comment by stnight** [comment]
Yes, i have.
By using **sdkman**, i have to downgrade the jdk version to version 8
